site_name: usmonaliyev99
site_description: My home
site_author: Usmonaliyev Temur

site_url: https://usmonaliyev99.github.io/usmonaliyev99/
repo_url: https://github.com/usmonaliyev99/

watch:
  - docs

theme:
  name: swan

nav:
  - Home: index.md
  - Packages: package.md
  - My trip: my-trip.md
  - Skills: skill.md
  - Contacts: contact.md
  - Docker:
    - Install: docker/install.md
    - Build: docker/build.md
    - Docker compose: docker/docker-compose.md
  - Kubernetes:
    - Minikube: kubernetes/minikube.md
    - k3s: kubernetes/k3s.md
    - helm: kubernetes/helm.md
  - Gitlab:
    - Setup gitlab server: gitlab/server.md
    - Install gitLab runner: gitlab/runner.md
    - Base image: gitlab/base-image.md
    - helm: gitlab/helm.md
    - CI/CD: gitlab/ci-cd.md


plugins:
  - search
  - termynal
